version: '3.8'

services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/mysql:/var/lib/mysql

  wordpress:
    image: wordpress:6.7.0-php8.2-apache
    restart: unless-stopped
    ports:
     - '4000:80'
    depends_on:
        mysql:
          condition: service_healthy
    environment:
        WORDPRESS_DB_HOST: mysql:3306
        WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
        WORDPRESS_DB_USER: ${MYSQL_USER}
        WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/wp:/var/www/html

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    ports:
      - '4001:80'
    depends_on:
      mysql:
        condition: service_healthy
    environment: 
        PMA_HOST: mysql
  
  nginx:
    image: nginx:1.26.3-alpine
